replicaCountSolver: 2
replicaCountWeb: 2
replicaCountBackend: 1

image:
  solver:
    repository: ghcr.io/elteammate/schedge-solver
    tag: latest
  backend:
    repository: ghcr.io/elteammate/schedge-backend
    tag: latest
  web:
    repository: ghcr.io/elteammate/schedge-frontend
    tag: latest

service:
  solver:
    port: 6000
    type: ClusterIP
  backend:
    port: 5000
    type: ClusterIP
  web:
    port: 80
    type: ClusterIP

environment:
  BACKEND_HOST_ADDRESS: 0.0.0.0
  BACKEND_PORT: 5000
  SOLVER_PORT: 6000
  SOLVER_ADDRESS: schedge-solver.default.svc.cluster.local
  SOLVER_SERVER_URL: http://schedge-solver.default.svc.cluster.local:6000/schedule
