apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedge-backend
spec:
  replicas: {{ .Values.replicaCountBackend | default 1 }}
  selector:
    matchLabels:
      app: schedge-backend
  template:
    metadata:
      labels:
        app: schedge-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          env:
            - name: BACKEND_HOST_ADDRESS
              value: 0.0.0.0