apiVersion: v1
kind: Service
metadata:
  name: schedge-solver
spec:
  type: {{ .Values.service.solver.type }}
  ports:
    - port: {{ .Values.service.solver.port }}
      targetPort: {{ .Values.service.solver.port }}
  selector:
    app: schedge-solver
