apiVersion: v1
kind: Service
metadata:
  name: schedge-backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
  selector:
    app: schedge-backend
