name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install backend dependencies
        run: |
          cd schedge-backend
          pip install --upgrade pip
          pip install -r ../requirements.txt
      - name: Run pytest
        run: |
          cd schedge-backend
          pytest --maxfail=1 --disable-warnings -q

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install frontend dependencies
        run: |
          cd schedge-web
          npm ci
      - name: Run Vitest
        run: |
          cd schedge-web
          npm test

  solver-tests:
    name: Solver (Rust) Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        run: |
          rustup toolchain install stable
          rustup default stable

      - name: Run cargo tests
        run: |
          cd schedge-solver
          cargo test --workspace --quiet

  solver-fuzzing:
    runs-on: ubuntu-latest

    env:
      CARGO_FUZZ_VERSION: 0.12.0
      FUZZ_TIME: 60

    strategy:
      matrix:
        include:
          - fuzz_target: mcs

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly
      - run: rustup default nightly

      - uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/cargo-fuzz
          key: cargo-fuzz-bin-${{ env.CARGO_FUZZ_VERSION }}

      - run: echo "${{ runner.tool_cache }}/cargo-fuzz/bin" >> $GITHUB_PATH
      - run: cargo install --root "${{ runner.tool_cache }}/cargo-fuzz" --version ${{ env.CARGO_FUZZ_VERSION }} cargo-fuzz --locked

      - run: cd schedge-solver && cargo fuzz build ${{ matrix.fuzz_target }}
      - run: cd schedge-solver && cargo fuzz run ${{ matrix.fuzz_target }} -- -max_total_time=${{ env.FUZZ_TIME }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: fuzzing-artifacts-${{ matrix.fuzz_target }}-${{ github.sha }}
          path: fuzz/artifacts

  system-tests:
    name: System API Tests
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MONGO_URI: mongodb://localhost:27017/schedge
      DB_NAME: schedge
      SOLVER_SERVER_URL: http://0.0.0.0:6000/schedule
      BACKEND_HOST_ADDRESS: localhost
      BACKEND_PORT: 5000
      BIND_ADDR: 0.0.0.0:6000
      VITE_API_BASE_URL: http://localhost:5000
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup toolchain install stable
          rustup default stable

      - name: Build solver binary
        run: |
          cd schedge-solver
          cargo build --release
      - name: Launch solver server
        run: |
          ./schedge-solver/target/release/schedge-solver-server &
          echo "Solver PID=$!"
        shell: bash

      - name: Wait for solver to be ready
        run: sleep 5

      - name: Set up Python & install backend
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install backend dependencies
        run: |
          cd schedge-backend
          pip install --upgrade pip
          pip install -r ../requirements.txt
      - name: Launch backend server
        run: |
          cd schedge-backend
          python main.py &
          echo "Backend PID=$!"
        shell: bash

      - name: Wait for backend to be ready
        run: sleep 5

      - name: Run system API tests
        run: |
          pytest schedge/tests/test_system_api.py
